const planetData = [
    {
        name: 'Mercury',
        color: "#717171",
        description: 'Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the planets in the Solar System.',
        xRadius: 5.5,
        zRadius: 5.5,
        size: 0.045,
        distance: 0.8,
        speed: 0.284090909,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_mercury.jpg',
        mapScale: 1,
        emissiveColor: "#8a8a8a",
        emissiveIntensity: 0.2,
        textColor: "#717171",
    },
    {
        name: 'Venus',
        color: "white",
        description: 'Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the second-brightest natural object in the night sky after the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in broad daylight.',
        xRadius: 10,
        zRadius: 10,
        size: 0.035,
        distance: 0.6,
        speed: 0.111111111,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_venus.jpg',
        mapScale: 0.01,
        emissiveColor: "#df9a33",
        emissiveIntensity: 0.2,
        textColor: "#9e3f04",
    },
    {
        name: 'Earth',
        color: "#9e3f04",
        description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other sources of evidence, Earth formed over 4.5 billion years ago.',
        xRadius: 15,
        zRadius: 15,
        size: 0.0298,
        distance: 0.8,
        speed: 0.068493151,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_earth.jpg',
        mapScale: 0.01,
        emissiveColor: "",
        emissiveIntensity: 0,
        textColor: "#19356b",
    },
    {
        name: 'Mars',
        color: "#e4a876",
        description: 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System after Mercury. In English, Mars carries a name of the Roman god of war and is often referred to as the "Red Planet".',
        xRadius: 19.5,
        zRadius: 19.5,
        size: 0.045,
        distance: 1,
        speed: 0.034246575,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_mars.jpg',
        mapScale: 0.01,
        emissiveColor: "#e66939",
        emissiveIntensity: 0.2,
        textColor: "#e4a876",
        testImage: '/images/icons/mars.png',
    },
    {
        name: 'Jupiter',
        color: "#856f57",
        description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined.',
        xRadius: 24,
        zRadius: 24,
        size: 0.09,
        distance: 1.2,
        speed: 0.005707763,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_jupiter.jpg',
        mapScale: 0.01,
        emissiveColor: "white",
        emissiveIntensity: 0.01,
        textColor: "#856f57",
    },
    {
        name: 'Saturn',
        color: "#cbae94",
        description: 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius about nine times that of Earth.',
        xRadius: 30,
        zRadius: 30,
        size: 0.088,
        distance: 1.4,
        speed: 0.002361833,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0,
        mapTexture: '/images/2k_saturn.jpg',
        mapScale: 0.01,
        emissiveColor: "black",
        emissiveIntensity: 1,
        textColor: "#cbae94",
    },
    {
        name: 'Uranus',
        color: "#c6eaed",
        description: 'Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.',
        xRadius: 35,
        zRadius: 35,
        size: 0.06,
        distance: 1.6,
        speed: 0.000815395,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_uranus.jpg',
        mapScale: 0.01,
        emissiveColor: "darkblue",
        emissiveIntensity: 1,
        textColor: "#c6eaed",
    },
    {
        name: 'Neptune',
        color: "wh#3889f3ite",
        description: 'Neptune is the eighth and farthest known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet.',
        xRadius: 40,
        zRadius: 40,
        size: 0.06,
        distance: 1.8,
        speed: 0.00041511,
        displacementTexture: '/images/2k_sun_displacement.png',
        displacementScale: 0.01,
        mapTexture: '/images/2k_neptune.jpg',
        mapScale: 0.01,
        emissiveColor: "white",
        emissiveIntensity: 0,
        textColor: "#3889f3",
    },
];

export default planetData;
